env: "local"
storage_path: "postgres://postgres:postgres@host.docker.internal:5432/postgres?sslmode=disable"
token_ttl: "3600s"
grpc:
  authPort: 50051
  accountPort: 50053
  timeout: "10s"
redis:
  storage: "localhost:6379"
  password: ""
  db: 0